version: "3.3"

services:
  app:
    container_name: cat
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m AM
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/catuserbot
    depends_on:
      - db
    volumes:
      - botdata:/userbot

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catuserbot
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  botdata:
    driver: local
